const FEATURE_DEFINITIONS = [
  { id: 'qol-001', name: 'Readability Feature 1', description: 'Improve readability with setting #1.', handler: 'fontScale', value: '1.05' },
  { id: 'qol-002', name: 'Focus Feature 2', description: 'Reduce distractions using option #2.', handler: 'lineHeight', value: '1.7' },
  { id: 'qol-003', name: 'Navigation Feature 3', description: 'Speed navigation with tool #3.', handler: 'letterSpacing', value: '0.02em' },
  { id: 'qol-004', name: 'Media Feature 4', description: 'Control media behavior with tweak #4.', handler: 'maxWidth', value: '78ch' },
  { id: 'qol-005', name: 'Forms Feature 5', description: 'Enhance forms with helper #5.', handler: 'paragraphSpacing', value: '1em' },
  { id: 'qol-006', name: 'Accessibility Feature 6', description: 'Improve accessibility with option #6.', handler: 'linkStyle', value: '#0ea5e9' },
  { id: 'qol-007', name: 'Productivity Feature 7', description: 'Boost productivity with helper #7.', handler: 'visitedColor', value: '#7c3aed' },
  { id: 'qol-008', name: 'Appearance Feature 8', description: 'Adjust page appearance with theme #8.', handler: 'focusRing', value: '#f59e0b' },
  { id: 'qol-009', name: 'Data Feature 9', description: 'Improve data scanning with aid #9.', handler: 'hideSticky', value: null },
  { id: 'qol-010', name: 'Utilities Feature 10', description: 'General utility feature #10.', handler: 'hideAds', value: null },
  { id: 'qol-011', name: 'Readability Feature 11', description: 'Improve readability with setting #11.', handler: 'hideOverlays', value: null },
  { id: 'qol-012', name: 'Focus Feature 12', description: 'Reduce distractions using option #12.', handler: 'imageFilter', value: 'brightness(0.9)' },
  { id: 'qol-013', name: 'Navigation Feature 13', description: 'Speed navigation with tool #13.', handler: 'imageHoverZoom', value: '1.05' },
  { id: 'qol-014', name: 'Media Feature 14', description: 'Control media behavior with tweak #14.', handler: 'disableAutoplay', value: null },
  { id: 'qol-015', name: 'Forms Feature 15', description: 'Enhance forms with helper #15.', handler: 'videoSpeed', value: '1.25' },
  { id: 'qol-016', name: 'Accessibility Feature 16', description: 'Improve accessibility with option #16.', handler: 'hideComments', value: null },
  { id: 'qol-017', name: 'Productivity Feature 17', description: 'Boost productivity with helper #17.', handler: 'hideSidebars', value: null },
  { id: 'qol-018', name: 'Appearance Feature 18', description: 'Adjust page appearance with theme #18.', handler: 'hideChat', value: null },
  { id: 'qol-019', name: 'Data Feature 19', description: 'Improve data scanning with aid #19.', handler: 'smoothScroll', value: null },
  { id: 'qol-020', name: 'Utilities Feature 20', description: 'General utility feature #20.', handler: 'scrollbarThin', value: null },
  { id: 'qol-021', name: 'Readability Feature 21', description: 'Improve readability with setting #21.', handler: 'reduceMotion', value: null },
  { id: 'qol-022', name: 'Focus Feature 22', description: 'Reduce distractions using option #22.', handler: 'filterPage', value: 'contrast(1.1)' },
  { id: 'qol-023', name: 'Navigation Feature 23', description: 'Speed navigation with tool #23.', handler: 'nightTint', value: 'rgba(255,170,120,0.1)' },
  { id: 'qol-024', name: 'Media Feature 24', description: 'Control media behavior with tweak #24.', handler: 'selectionStyle', value: '#fde68a' },
  { id: 'qol-025', name: 'Forms Feature 25', description: 'Enhance forms with helper #25.', handler: 'codeFont', value: null },
  { id: 'qol-026', name: 'Accessibility Feature 26', description: 'Improve accessibility with option #26.', handler: 'tableZebra', value: null },
  { id: 'qol-027', name: 'Productivity Feature 27', description: 'Boost productivity with helper #27.', handler: 'inputGlow', value: null },
  { id: 'qol-028', name: 'Appearance Feature 28', description: 'Adjust page appearance with theme #28.', handler: 'buttonRadius', value: '12px' },
  { id: 'qol-029', name: 'Data Feature 29', description: 'Improve data scanning with aid #29.', handler: 'linkHover', value: null },
  { id: 'qol-030', name: 'Utilities Feature 30', description: 'General utility feature #30.', handler: 'readingProgress', value: null },
  { id: 'qol-031', name: 'Readability Feature 31', description: 'Improve readability with setting #31.', handler: 'readingTime', value: null },
  { id: 'qol-032', name: 'Focus Feature 32', description: 'Reduce distractions using option #32.', handler: 'restoreContextMenu', value: null },
  { id: 'qol-033', name: 'Navigation Feature 33', description: 'Speed navigation with tool #33.', handler: 'restoreTextSelect', value: null },
  { id: 'qol-034', name: 'Media Feature 34', description: 'Control media behavior with tweak #34.', handler: 'stripTracking', value: null },
  { id: 'qol-035', name: 'Forms Feature 35', description: 'Enhance forms with helper #35.', handler: 'externalNewTab', value: null },
  { id: 'qol-036', name: 'Accessibility Feature 36', description: 'Improve accessibility with option #36.', handler: 'autosaveTextareas', value: null },
  { id: 'qol-037', name: 'Productivity Feature 37', description: 'Boost productivity with helper #37.', handler: 'wordCounter', value: null },
  { id: 'qol-038', name: 'Appearance Feature 38', description: 'Adjust page appearance with theme #38.', handler: 'cornerClock', value: null },
  { id: 'qol-039', name: 'Data Feature 39', description: 'Improve data scanning with aid #39.', handler: 'hideCookies', value: null },
  { id: 'qol-040', name: 'Utilities Feature 40', description: 'General utility feature #40.', handler: 'focusMode', value: null },
  { id: 'qol-041', name: 'Readability Feature 41', description: 'Improve readability with setting #41.', handler: 'generateTOC', value: null },
  { id: 'qol-042', name: 'Focus Feature 42', description: 'Reduce distractions using option #42.', handler: 'headingsHighlight', value: null },
  { id: 'qol-043', name: 'Navigation Feature 43', description: 'Speed navigation with tool #43.', handler: 'blockquoteStyle', value: null },
  { id: 'qol-044', name: 'Media Feature 44', description: 'Control media behavior with tweak #44.', handler: 'listIndent', value: null },
  { id: 'qol-045', name: 'Forms Feature 45', description: 'Enhance forms with helper #45.', handler: 'stickyNote', value: null },
  { id: 'qol-046', name: 'Accessibility Feature 46', description: 'Improve accessibility with option #46.', handler: 'backToTop', value: null },
  { id: 'qol-047', name: 'Productivity Feature 47', description: 'Boost productivity with helper #47.', handler: 'jumpToBottom', value: null },
  { id: 'qol-048', name: 'Appearance Feature 48', description: 'Adjust page appearance with theme #48.', handler: 'dragScroll', value: null },
  { id: 'qol-049', name: 'Data Feature 49', description: 'Improve data scanning with aid #49.', handler: 'linkTooltip', value: null },
  { id: 'qol-050', name: 'Utilities Feature 50', description: 'General utility feature #50.', handler: 'domainBadge', value: '1.05' },
  { id: 'qol-051', name: 'Readability Feature 51', description: 'Improve readability with setting #51.', handler: 'fontScale', value: '1.7' },
  { id: 'qol-052', name: 'Focus Feature 52', description: 'Reduce distractions using option #52.', handler: 'lineHeight', value: '0.02em' },
  { id: 'qol-053', name: 'Navigation Feature 53', description: 'Speed navigation with tool #53.', handler: 'letterSpacing', value: '78ch' },
  { id: 'qol-054', name: 'Media Feature 54', description: 'Control media behavior with tweak #54.', handler: 'maxWidth', value: '1em' },
  { id: 'qol-055', name: 'Forms Feature 55', description: 'Enhance forms with helper #55.', handler: 'paragraphSpacing', value: '#0ea5e9' },
  { id: 'qol-056', name: 'Accessibility Feature 56', description: 'Improve accessibility with option #56.', handler: 'linkStyle', value: '#7c3aed' },
  { id: 'qol-057', name: 'Productivity Feature 57', description: 'Boost productivity with helper #57.', handler: 'visitedColor', value: '#f59e0b' },
  { id: 'qol-058', name: 'Appearance Feature 58', description: 'Adjust page appearance with theme #58.', handler: 'focusRing', value: null },
  { id: 'qol-059', name: 'Data Feature 59', description: 'Improve data scanning with aid #59.', handler: 'hideSticky', value: null },
  { id: 'qol-060', name: 'Utilities Feature 60', description: 'General utility feature #60.', handler: 'hideAds', value: null },
  { id: 'qol-061', name: 'Readability Feature 61', description: 'Improve readability with setting #61.', handler: 'hideOverlays', value: 'brightness(0.9)' },
  { id: 'qol-062', name: 'Focus Feature 62', description: 'Reduce distractions using option #62.', handler: 'imageFilter', value: '1.05' },
  { id: 'qol-063', name: 'Navigation Feature 63', description: 'Speed navigation with tool #63.', handler: 'imageHoverZoom', value: null },
  { id: 'qol-064', name: 'Media Feature 64', description: 'Control media behavior with tweak #64.', handler: 'disableAutoplay', value: '1.25' },
  { id: 'qol-065', name: 'Forms Feature 65', description: 'Enhance forms with helper #65.', handler: 'videoSpeed', value: null },
  { id: 'qol-066', name: 'Accessibility Feature 66', description: 'Improve accessibility with option #66.', handler: 'hideComments', value: null },
  { id: 'qol-067', name: 'Productivity Feature 67', description: 'Boost productivity with helper #67.', handler: 'hideSidebars', value: null },
  { id: 'qol-068', name: 'Appearance Feature 68', description: 'Adjust page appearance with theme #68.', handler: 'hideChat', value: null },
  { id: 'qol-069', name: 'Data Feature 69', description: 'Improve data scanning with aid #69.', handler: 'smoothScroll', value: null },
  { id: 'qol-070', name: 'Utilities Feature 70', description: 'General utility feature #70.', handler: 'scrollbarThin', value: null },
  { id: 'qol-071', name: 'Readability Feature 71', description: 'Improve readability with setting #71.', handler: 'reduceMotion', value: 'contrast(1.1)' },
  { id: 'qol-072', name: 'Focus Feature 72', description: 'Reduce distractions using option #72.', handler: 'filterPage', value: 'rgba(255,170,120,0.1)' },
  { id: 'qol-073', name: 'Navigation Feature 73', description: 'Speed navigation with tool #73.', handler: 'nightTint', value: '#fde68a' },
  { id: 'qol-074', name: 'Media Feature 74', description: 'Control media behavior with tweak #74.', handler: 'selectionStyle', value: null },
  { id: 'qol-075', name: 'Forms Feature 75', description: 'Enhance forms with helper #75.', handler: 'codeFont', value: null },
  { id: 'qol-076', name: 'Accessibility Feature 76', description: 'Improve accessibility with option #76.', handler: 'tableZebra', value: null },
  { id: 'qol-077', name: 'Productivity Feature 77', description: 'Boost productivity with helper #77.', handler: 'inputGlow', value: '12px' },
  { id: 'qol-078', name: 'Appearance Feature 78', description: 'Adjust page appearance with theme #78.', handler: 'buttonRadius', value: null },
  { id: 'qol-079', name: 'Data Feature 79', description: 'Improve data scanning with aid #79.', handler: 'linkHover', value: null },
  { id: 'qol-080', name: 'Utilities Feature 80', description: 'General utility feature #80.', handler: 'readingProgress', value: null },
  { id: 'qol-081', name: 'Readability Feature 81', description: 'Improve readability with setting #81.', handler: 'readingTime', value: null },
  { id: 'qol-082', name: 'Focus Feature 82', description: 'Reduce distractions using option #82.', handler: 'restoreContextMenu', value: null },
  { id: 'qol-083', name: 'Navigation Feature 83', description: 'Speed navigation with tool #83.', handler: 'restoreTextSelect', value: null },
  { id: 'qol-084', name: 'Media Feature 84', description: 'Control media behavior with tweak #84.', handler: 'stripTracking', value: null },
  { id: 'qol-085', name: 'Forms Feature 85', description: 'Enhance forms with helper #85.', handler: 'externalNewTab', value: null },
  { id: 'qol-086', name: 'Accessibility Feature 86', description: 'Improve accessibility with option #86.', handler: 'autosaveTextareas', value: null },
  { id: 'qol-087', name: 'Productivity Feature 87', description: 'Boost productivity with helper #87.', handler: 'wordCounter', value: null },
  { id: 'qol-088', name: 'Appearance Feature 88', description: 'Adjust page appearance with theme #88.', handler: 'cornerClock', value: null },
  { id: 'qol-089', name: 'Data Feature 89', description: 'Improve data scanning with aid #89.', handler: 'hideCookies', value: null },
  { id: 'qol-090', name: 'Utilities Feature 90', description: 'General utility feature #90.', handler: 'focusMode', value: null },
  { id: 'qol-091', name: 'Readability Feature 91', description: 'Improve readability with setting #91.', handler: 'generateTOC', value: null },
  { id: 'qol-092', name: 'Focus Feature 92', description: 'Reduce distractions using option #92.', handler: 'headingsHighlight', value: null },
  { id: 'qol-093', name: 'Navigation Feature 93', description: 'Speed navigation with tool #93.', handler: 'blockquoteStyle', value: null },
  { id: 'qol-094', name: 'Media Feature 94', description: 'Control media behavior with tweak #94.', handler: 'listIndent', value: null },
  { id: 'qol-095', name: 'Forms Feature 95', description: 'Enhance forms with helper #95.', handler: 'stickyNote', value: null },
  { id: 'qol-096', name: 'Accessibility Feature 96', description: 'Improve accessibility with option #96.', handler: 'backToTop', value: null },
  { id: 'qol-097', name: 'Productivity Feature 97', description: 'Boost productivity with helper #97.', handler: 'jumpToBottom', value: null },
  { id: 'qol-098', name: 'Appearance Feature 98', description: 'Adjust page appearance with theme #98.', handler: 'dragScroll', value: null },
  { id: 'qol-099', name: 'Data Feature 99', description: 'Improve data scanning with aid #99.', handler: 'linkTooltip', value: '1.05' },
  { id: 'qol-100', name: 'Utilities Feature 100', description: 'General utility feature #100.', handler: 'domainBadge', value: '1.7' },
  { id: 'qol-101', name: 'Readability Feature 101', description: 'Improve readability with setting #101.', handler: 'fontScale', value: '0.02em' },
  { id: 'qol-102', name: 'Focus Feature 102', description: 'Reduce distractions using option #102.', handler: 'lineHeight', value: '78ch' },
  { id: 'qol-103', name: 'Navigation Feature 103', description: 'Speed navigation with tool #103.', handler: 'letterSpacing', value: '1em' },
  { id: 'qol-104', name: 'Media Feature 104', description: 'Control media behavior with tweak #104.', handler: 'maxWidth', value: '#0ea5e9' },
  { id: 'qol-105', name: 'Forms Feature 105', description: 'Enhance forms with helper #105.', handler: 'paragraphSpacing', value: '#7c3aed' },
  { id: 'qol-106', name: 'Accessibility Feature 106', description: 'Improve accessibility with option #106.', handler: 'linkStyle', value: '#f59e0b' },
  { id: 'qol-107', name: 'Productivity Feature 107', description: 'Boost productivity with helper #107.', handler: 'visitedColor', value: null },
  { id: 'qol-108', name: 'Appearance Feature 108', description: 'Adjust page appearance with theme #108.', handler: 'focusRing', value: null },
  { id: 'qol-109', name: 'Data Feature 109', description: 'Improve data scanning with aid #109.', handler: 'hideSticky', value: null },
  { id: 'qol-110', name: 'Utilities Feature 110', description: 'General utility feature #110.', handler: 'hideAds', value: 'brightness(0.9)' },
  { id: 'qol-111', name: 'Readability Feature 111', description: 'Improve readability with setting #111.', handler: 'hideOverlays', value: '1.05' },
  { id: 'qol-112', name: 'Focus Feature 112', description: 'Reduce distractions using option #112.', handler: 'imageFilter', value: null },
  { id: 'qol-113', name: 'Navigation Feature 113', description: 'Speed navigation with tool #113.', handler: 'imageHoverZoom', value: '1.25' },
  { id: 'qol-114', name: 'Media Feature 114', description: 'Control media behavior with tweak #114.', handler: 'disableAutoplay', value: null },
  { id: 'qol-115', name: 'Forms Feature 115', description: 'Enhance forms with helper #115.', handler: 'videoSpeed', value: null },
  { id: 'qol-116', name: 'Accessibility Feature 116', description: 'Improve accessibility with option #116.', handler: 'hideComments', value: null },
  { id: 'qol-117', name: 'Productivity Feature 117', description: 'Boost productivity with helper #117.', handler: 'hideSidebars', value: null },
  { id: 'qol-118', name: 'Appearance Feature 118', description: 'Adjust page appearance with theme #118.', handler: 'hideChat', value: null },
  { id: 'qol-119', name: 'Data Feature 119', description: 'Improve data scanning with aid #119.', handler: 'smoothScroll', value: null },
  { id: 'qol-120', name: 'Utilities Feature 120', description: 'General utility feature #120.', handler: 'scrollbarThin', value: 'contrast(1.1)' },
  { id: 'qol-121', name: 'Readability Feature 121', description: 'Improve readability with setting #121.', handler: 'reduceMotion', value: 'rgba(255,170,120,0.1)' },
  { id: 'qol-122', name: 'Focus Feature 122', description: 'Reduce distractions using option #122.', handler: 'filterPage', value: '#fde68a' },
  { id: 'qol-123', name: 'Navigation Feature 123', description: 'Speed navigation with tool #123.', handler: 'nightTint', value: null },
  { id: 'qol-124', name: 'Media Feature 124', description: 'Control media behavior with tweak #124.', handler: 'selectionStyle', value: null },
  { id: 'qol-125', name: 'Forms Feature 125', description: 'Enhance forms with helper #125.', handler: 'codeFont', value: null },
  { id: 'qol-126', name: 'Accessibility Feature 126', description: 'Improve accessibility with option #126.', handler: 'tableZebra', value: '12px' },
  { id: 'qol-127', name: 'Productivity Feature 127', description: 'Boost productivity with helper #127.', handler: 'inputGlow', value: null },
  { id: 'qol-128', name: 'Appearance Feature 128', description: 'Adjust page appearance with theme #128.', handler: 'buttonRadius', value: null },
  { id: 'qol-129', name: 'Data Feature 129', description: 'Improve data scanning with aid #129.', handler: 'linkHover', value: null },
  { id: 'qol-130', name: 'Utilities Feature 130', description: 'General utility feature #130.', handler: 'readingProgress', value: null },
  { id: 'qol-131', name: 'Readability Feature 131', description: 'Improve readability with setting #131.', handler: 'readingTime', value: null },
  { id: 'qol-132', name: 'Focus Feature 132', description: 'Reduce distractions using option #132.', handler: 'restoreContextMenu', value: null },
  { id: 'qol-133', name: 'Navigation Feature 133', description: 'Speed navigation with tool #133.', handler: 'restoreTextSelect', value: null },
  { id: 'qol-134', name: 'Media Feature 134', description: 'Control media behavior with tweak #134.', handler: 'stripTracking', value: null },
  { id: 'qol-135', name: 'Forms Feature 135', description: 'Enhance forms with helper #135.', handler: 'externalNewTab', value: null },
  { id: 'qol-136', name: 'Accessibility Feature 136', description: 'Improve accessibility with option #136.', handler: 'autosaveTextareas', value: null },
  { id: 'qol-137', name: 'Productivity Feature 137', description: 'Boost productivity with helper #137.', handler: 'wordCounter', value: null },
  { id: 'qol-138', name: 'Appearance Feature 138', description: 'Adjust page appearance with theme #138.', handler: 'cornerClock', value: null },
  { id: 'qol-139', name: 'Data Feature 139', description: 'Improve data scanning with aid #139.', handler: 'hideCookies', value: null },
  { id: 'qol-140', name: 'Utilities Feature 140', description: 'General utility feature #140.', handler: 'focusMode', value: null },
  { id: 'qol-141', name: 'Readability Feature 141', description: 'Improve readability with setting #141.', handler: 'generateTOC', value: null },
  { id: 'qol-142', name: 'Focus Feature 142', description: 'Reduce distractions using option #142.', handler: 'headingsHighlight', value: null },
  { id: 'qol-143', name: 'Navigation Feature 143', description: 'Speed navigation with tool #143.', handler: 'blockquoteStyle', value: null },
  { id: 'qol-144', name: 'Media Feature 144', description: 'Control media behavior with tweak #144.', handler: 'listIndent', value: null },
  { id: 'qol-145', name: 'Forms Feature 145', description: 'Enhance forms with helper #145.', handler: 'stickyNote', value: null },
  { id: 'qol-146', name: 'Accessibility Feature 146', description: 'Improve accessibility with option #146.', handler: 'backToTop', value: null },
  { id: 'qol-147', name: 'Productivity Feature 147', description: 'Boost productivity with helper #147.', handler: 'jumpToBottom', value: null },
  { id: 'qol-148', name: 'Appearance Feature 148', description: 'Adjust page appearance with theme #148.', handler: 'dragScroll', value: '1.05' },
  { id: 'qol-149', name: 'Data Feature 149', description: 'Improve data scanning with aid #149.', handler: 'linkTooltip', value: '1.7' },
  { id: 'qol-150', name: 'Utilities Feature 150', description: 'General utility feature #150.', handler: 'domainBadge', value: '0.02em' }
];
const STYLE_ID = 'mega-qol-style';
const handlerMap = {
  fontScale: value => injectCss(`html{font-size:${value}em !important;}`),
  lineHeight: value => injectCss(`body{line-height:${value} !important;}`),
  letterSpacing: value => injectCss(`body{letter-spacing:${value} !important;}`),
  maxWidth: value => injectCss(`article,main,[role=main]{max-width:${value} !important;margin:auto !important;}`),
  paragraphSpacing: value => injectCss(`p{margin-block:${value} !important;}`),
  linkStyle: value => injectCss(`a{color:${value} !important;text-decoration:underline !important;}`),
  visitedColor: value => injectCss(`a:visited{color:${value} !important;}`),
  focusRing: value => injectCss(`*:focus-visible{outline:3px solid ${value} !important;}`),
  hideSticky: ()=> injectCss(`.sticky,[class*=sticky],[style*=sticky]{position:static !important;}`),
  hideAds: ()=> injectCss(`[id*=ad],[class*=ad-],[class*=ads]{display:none !important;}`),
  hideOverlays: ()=> injectCss(`[role=dialog],.modal,.overlay{display:none !important;}`),
  imageFilter: value=> injectCss(`img{filter:${value} !important;}`),
  imageHoverZoom: value=> injectCss(`img:hover{transform:scale(${value});}`),
  disableAutoplay: ()=> document.querySelectorAll('video,audio').forEach(m=>{m.autoplay=false;m.pause?.();}),
  videoSpeed: value=> document.querySelectorAll('video').forEach(v=>v.playbackRate=Number(value)),
  hideComments: ()=> injectCss(`#comments,.comments,[class*=comment]{display:none !important;}`),
  hideSidebars: ()=> injectCss(`aside,.sidebar,[class*=sidebar]{display:none !important;}`),
  hideChat: ()=> injectCss(`[id*=chat],[class*=chat]{display:none !important;}`),
  smoothScroll: ()=> injectCss(`html{scroll-behavior:smooth !important;}`),
  scrollbarThin: ()=> injectCss(`::-webkit-scrollbar{width:8px;height:8px;}`),
  reduceMotion: ()=> injectCss(`*,*:before,*:after{animation:none !important;transition:none !important;}`),
  filterPage: value=> document.documentElement.style.filter=value,
  nightTint: value=> addOverlay(value),
  selectionStyle: value=> injectCss(`::selection{background:${value};}`),
  codeFont: ()=> injectCss(`pre,code{font-family:ui-monospace,monospace !important;}`),
  tableZebra: ()=> injectCss(`tr:nth-child(even){background:rgba(148,163,184,.13) !important;}`),
  inputGlow: ()=> injectCss(`input:focus,textarea:focus{box-shadow:0 0 0 3px rgba(59,130,246,.35) !important;}`),
  buttonRadius: value=> injectCss(`button{border-radius:${value} !important;}`),
  linkHover: ()=> injectCss(`a:hover{background:rgba(56,189,248,.14) !important;}`),
  readingProgress: ()=>createReadingProgress(),
  readingTime: ()=>createReadingTimeBadge(),
  restoreContextMenu: ()=>document.addEventListener('contextmenu',e=>e.stopPropagation(),true),
  restoreTextSelect: ()=>injectCss(`*{user-select:text !important;}`),
  stripTracking: ()=>document.querySelectorAll('a[href]').forEach(a=>{try{const u=new URL(a.href);['utm_source','utm_medium','utm_campaign','fbclid','gclid'].forEach(k=>u.searchParams.delete(k));a.href=u.toString();}catch{}}),
  externalNewTab: ()=>document.querySelectorAll('a[href^="http"]').forEach(a=>{if(a.hostname!==location.hostname){a.target='_blank';a.rel='noopener noreferrer';}}),
  autosaveTextareas: ()=>document.querySelectorAll('textarea').forEach((t,i)=>{const k=`mq:${location.pathname}:${i}`;if(!t.value)t.value=localStorage.getItem(k)||'';t.oninput=()=>localStorage.setItem(k,t.value)}),
  wordCounter: ()=>document.querySelectorAll('textarea').forEach(t=>{const d=document.createElement('div');d.style.cssText='font:11px sans-serif;opacity:.7';const r=()=>d.textContent=`Words: ${t.value.trim()?t.value.trim().split(/\s+/).length:0}`;t.after(d);t.addEventListener('input',r);r();}),
  cornerClock: ()=>{if(document.getElementById('mq-clock'))return;const d=document.createElement('div');d.id='mq-clock';d.style.cssText='position:fixed;top:10px;right:10px;z-index:999999;background:#111;color:#fff;padding:4px 8px;border-radius:6px;font:11px sans-serif';document.body.appendChild(d);setInterval(()=>d.textContent=new Date().toLocaleTimeString(),1000);},
  hideCookies: ()=> injectCss(`[id*=cookie],[class*=cookie]{display:none !important;}`),
  focusMode: ()=> injectCss(`header,footer,aside,nav{opacity:.25 !important;}`),
  generateTOC: ()=>generateTOC(),
  headingsHighlight: ()=>injectCss(`h1,h2,h3{background:linear-gradient(transparent 68%, rgba(250,204,21,.25) 0) !important;}`),
  blockquoteStyle: ()=>injectCss(`blockquote{border-left:4px solid #38bdf8;padding-left:1em;background:rgba(56,189,248,.08);}`),
  listIndent: ()=>injectCss(`ul,ol{padding-left:2.2rem !important;}`),
  stickyNote: ()=>addStickyNote(),
  backToTop: ()=>addJump('↑',()=>scrollTo({top:0,behavior:'smooth'}),12),
  jumpToBottom: ()=>addJump('↓',()=>scrollTo({top:document.body.scrollHeight,behavior:'smooth'}),52),
  dragScroll: ()=>enableDragScroll(),
  linkTooltip: ()=>document.querySelectorAll('a[href]').forEach(a=>{if(!a.title)a.title=a.href}),
  domainBadge: ()=>{if(document.getElementById('mq-domain'))return;const d=document.createElement('div');d.id='mq-domain';d.textContent=location.hostname;d.style.cssText='position:fixed;left:10px;top:10px;z-index:999999;background:#1d4ed8;color:#fff;padding:4px 8px;border-radius:999px;font:11px sans-serif';document.body.appendChild(d);}
};
function injectCss(rule){const s=document.getElementById(STYLE_ID)||Object.assign(document.createElement('style'),{id:STYLE_ID});s.textContent+=`
${rule}`;document.head.appendChild(s)}
function addOverlay(color){if(document.getElementById('mq-overlay'))return;const d=document.createElement('div');d.id='mq-overlay';d.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:999998';d.style.background=color;document.body.appendChild(d)}
function createReadingProgress(){if(document.getElementById('mq-progress'))return;const d=document.createElement('div');d.id='mq-progress';d.style.cssText='position:fixed;top:0;left:0;height:3px;background:#22c55e;width:0;z-index:999999';document.body.appendChild(d);addEventListener('scroll',()=>{const h=document.documentElement;const p=(h.scrollTop)/(h.scrollHeight-h.clientHeight);d.style.width=`${Math.max(0,Math.min(1,p))*100}%`;},{passive:true});}
function createReadingTimeBadge(){if(document.getElementById('mq-read'))return;const m=Math.max(1,Math.round(document.body.innerText.trim().split(/\s+/).length/220));const d=document.createElement('div');d.id='mq-read';d.textContent=`${m} min read`;d.style.cssText='position:fixed;bottom:10px;left:10px;z-index:999999;background:#111;color:#fff;padding:4px 8px;border-radius:999px;font:11px sans-serif';document.body.appendChild(d)}
function generateTOC(){if(document.getElementById('mq-toc'))return;const hs=[...document.querySelectorAll('h1,h2,h3')].slice(0,30);if(!hs.length)return;const d=document.createElement('div');d.id='mq-toc';d.style.cssText='position:fixed;right:10px;top:50px;max-height:60vh;overflow:auto;z-index:999999;background:#fff;border:1px solid #cbd5e1;padding:8px;border-radius:8px;font:12px sans-serif';d.innerHTML='<strong>On this page</strong>';hs.forEach((h,i)=>{if(!h.id)h.id=`mqh${i}`;const a=document.createElement('a');a.href='#'+h.id;a.textContent=h.textContent.trim().slice(0,50);a.style.display='block';a.style.margin='4px 0';d.appendChild(a)});document.body.appendChild(d)}
function addStickyNote(){if(document.getElementById('mq-note'))return;const t=document.createElement('textarea');t.id='mq-note';t.style.cssText='position:fixed;left:10px;bottom:10px;width:220px;height:120px;z-index:999999;background:#fef9c3;border:1px solid #f59e0b;border-radius:8px;padding:8px;font:12px sans-serif';t.value=localStorage.getItem('mq-note')||'';t.oninput=()=>localStorage.setItem('mq-note',t.value);document.body.appendChild(t)}
function addJump(symbol,cb,bottom){const id='mq-j'+symbol;if(document.getElementById(id))return;const b=document.createElement('button');b.id=id;b.textContent=symbol;b.style.cssText=`position:fixed;right:10px;bottom:${bottom}px;z-index:999999;background:#111;color:#fff;border:none;border-radius:999px;width:32px;height:32px`;b.onclick=cb;document.body.appendChild(b)}
function enableDragScroll(){let on=false,startY=0,startTop=0;addEventListener('mousedown',e=>{if(!e.altKey)return;on=true;startY=e.clientY;startTop=scrollY;document.body.style.userSelect='none'});addEventListener('mousemove',e=>{if(!on)return;scrollTo({top:startTop-(e.clientY-startY)})});addEventListener('mouseup',()=>{on=false;document.body.style.userSelect=''})}
function applyFeatures(active){for(const f of FEATURE_DEFINITIONS){if(!active[f.id])continue;const fn=handlerMap[f.handler];if(typeof fn==='function')fn(f.value);}}
chrome.storage.sync.get(['enabledFeatures'],({enabledFeatures={}})=>applyFeatures(enabledFeatures));
chrome.runtime.onMessage.addListener(msg=>{if(msg?.type==='featuresUpdated')location.reload()});
